/*
 * Copyright (c) 2025, Petr Bena <petr@bena.rocks>
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 * 1. Redistributions of source code must retain the above copyright notice,
 *    this list of conditions and the following disclaimer.
 *
 * 2. Redistributions in binary form must reproduce the above copyright notice,
 *    this list of conditions and the following disclaimer in the documentation
 *    and/or other materials provided with the distribution.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
 * LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
 * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
 * CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 */

#include "vif.h"
#include "network/connection.h"
#include "../xencache.h"
#include "network.h"
#include "vm.h"

VIF::VIF(XenConnection* connection, const QString& opaqueRef, QObject* parent) : XenObject(connection, opaqueRef, parent)
{
}

QStringList VIF::AllowedOperations() const
{
    return this->stringListProperty("allowed_operations");
}

QVariantMap VIF::CurrentOperations() const
{
    return this->property("current_operations").toMap();
}

QString VIF::GetDevice() const
{
    return this->stringProperty("device");
}

QString VIF::GetNetworkRef() const
{
    return this->stringProperty("network");
}

QString VIF::GetVMRef() const
{
    return this->stringProperty("VM");
}

QString VIF::GetMAC() const
{
    return this->stringProperty("MAC");
}

qint64 VIF::GetMTU() const
{
    return this->longProperty("MTU", 1500);
}

bool VIF::IsCurrentlyAttached() const
{
    return this->boolProperty("currently_attached", false);
}

qint64 VIF::GetStatusCode() const
{
    return this->longProperty("status_code", 0);
}

QString VIF::StatusDetail() const
{
    return this->stringProperty("status_detail");
}

QVariantMap VIF::RuntimeProperties() const
{
    return this->property("runtime_properties").toMap();
}

QString VIF::QosAlgorithmType() const
{
    return this->stringProperty("qos_algorithm_type");
}

QVariantMap VIF::QosAlgorithmParams() const
{
    return this->property("qos_algorithm_params").toMap();
}

QStringList VIF::QosSupportedAlgorithms() const
{
    return this->stringListProperty("qos_supported_algorithms");
}

QString VIF::MetricsRef() const
{
    return this->stringProperty("metrics");
}

bool VIF::MACAutogenerated() const
{
    return this->boolProperty("MAC_autogenerated", false);
}

QString VIF::LockingMode() const
{
    return this->stringProperty("locking_mode", "network_default");
}

QStringList VIF::Ipv4Allowed() const
{
    return this->stringListProperty("ipv4_allowed");
}

QStringList VIF::Ipv6Allowed() const
{
    return this->stringListProperty("ipv6_allowed");
}

QString VIF::Ipv4ConfigurationMode() const
{
    return this->stringProperty("ipv4_configuration_mode", "None");
}

QStringList VIF::Ipv4Addresses() const
{
    return this->stringListProperty("ipv4_addresses");
}

QString VIF::Ipv4Gateway() const
{
    return this->stringProperty("ipv4_gateway");
}

QString VIF::Ipv6ConfigurationMode() const
{
    return this->stringProperty("ipv6_configuration_mode", "None");
}

QStringList VIF::Ipv6Addresses() const
{
    return this->stringListProperty("ipv6_addresses");
}

QString VIF::Ipv6Gateway() const
{
    return this->stringProperty("ipv6_gateway");
}

QSharedPointer<Network> VIF::GetNetwork() const
{
    XenConnection* connection = this->GetConnection();
    if (!connection)
        return QSharedPointer<Network>();
    
    XenCache* cache = connection->GetCache();
    
    QString ref = this->GetNetworkRef();
    if (ref.isEmpty() || ref == XENOBJECT_NULL)
        return QSharedPointer<Network>();
    
    return cache->ResolveObject<Network>(ref);
}

QSharedPointer<VM> VIF::GetVM() const
{
    XenConnection* connection = this->GetConnection();
    if (!connection)
        return QSharedPointer<VM>();
    
    XenCache* cache = connection->GetCache();
    
    QString ref = this->GetVMRef();
    if (ref.isEmpty() || ref == XENOBJECT_NULL)
        return QSharedPointer<VM>();

    return cache->ResolveObject<VM>(XenObjectType::VM, ref);
}
