/*
 * Copyright (c) 2025, Petr Bena <petr@bena.rocks>
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 * 1. Redistributions of source code must retain the above copyright notice,
 *    this list of conditions and the following disclaimer.
 *
 * 2. Redistributions in binary form must reproduce the above copyright notice,
 *    this list of conditions and the following disclaimer in the documentation
 *    and/or other materials provided with the distribution.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
 * LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
 * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
 * CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 */

#ifndef VIF_H
#define VIF_H

#include "xenobject.h"

class Network;
class VM;

/**
 * @brief VIF - A virtual network interface
 *
 * Qt equivalent of C# XenAPI.VIF class. Represents a virtual network interface.
 *
 * Key properties (from C# VIF class):
 * - device (order in which VIF backends are created)
 * - network (virtual network this VIF is connected to)
 * - VM (virtual machine this VIF is connected to)
 * - MAC (ethernet MAC address)
 * - MTU (maximum transmission unit)
 * - currently_attached (whether device is currently attached)
 * - locking_mode (network locking mode)
 * - ipv4_allowed, ipv6_allowed (IP filtering)
 * - qos_algorithm_type, qos_algorithm_params (QoS settings)
 *
 * First published in XenServer 4.0.
 */
class XENLIB_EXPORT VIF : public XenObject
{
    Q_OBJECT

    public:
        explicit VIF(XenConnection* connection, const QString& opaqueRef, QObject* parent = nullptr);
        ~VIF() override = default;

        //! Get allowed VIF operations (first published in XenServer 4.0)
        QStringList AllowedOperations() const;

        //! Get current operations (map of task ID to operation type, first published in XenServer 4.0)
        QVariantMap CurrentOperations() const;

        //! Get device order in which VIF backends are created by xapi (e.g., "0", "1", "2", first published in XenServer 4.0)
        QString GetDevice() const;

        //! Get network opaque reference this VIF is connected to (first published in XenServer 4.0)
        QString GetNetworkRef() const;

        //! Get VM opaque reference this VIF is connected to (first published in XenServer 4.0)
        QString GetVMRef() const;

        //! Get ethernet MAC address as exposed to guest (first published in XenServer 4.0)
        QString GetMAC() const;

        //! Get MTU in octets (first published in XenServer 4.0)
        qint64 GetMTU() const;

        //! Check if device is currently attached (erased on reboot, first published in XenServer 4.0)
        bool IsCurrentlyAttached() const;

        //! Get error/success code from last attach-operation (erased on reboot, first published in XenServer 4.0)
        qint64 GetStatusCode() const;

        //! Get error/success information from last attach-operation status (first published in XenServer 4.0)
        QString StatusDetail() const;

        //! Get device runtime properties (first published in XenServer 4.0)
        QVariantMap RuntimeProperties() const;

        //! Get QoS algorithm to use (first published in XenServer 4.0)
        QString QosAlgorithmType() const;

        //! Get parameters for chosen QoS algorithm (first published in XenServer 4.0)
        QVariantMap QosAlgorithmParams() const;

        //! Get supported QoS algorithms for this VIF (first published in XenServer 4.0)
        QStringList QosSupportedAlgorithms() const;

        //! Get VIF_metrics opaque reference (first published in XenServer 4.0, deprecated since XenServer 6.1)
        QString MetricsRef() const;

        //! Check if MAC was autogenerated (first published in XenServer 5.5)
        bool MACAutogenerated() const;

        //! Get current locking mode ("network_default", "locked", "unlocked", "disabled", first published in XenServer 6.1)
        QString LockingMode() const;

        //! Get IPv4 addresses for traffic filtering (first published in XenServer 6.1)
        QStringList Ipv4Allowed() const;

        //! Get IPv6 addresses for traffic filtering (first published in XenServer 6.1)
        QStringList Ipv6Allowed() const;

        //! Get IPv4 configuration mode ("None", "Static", first published in XenServer 7.0)
        QString Ipv4ConfigurationMode() const;

        //! Get IPv4 addresses in CIDR format (first published in XenServer 7.0)
        QStringList Ipv4Addresses() const;

        //! Get IPv4 gateway (empty string means no gateway is set, first published in XenServer 7.0)
        QString Ipv4Gateway() const;

        //! Get IPv6 configuration mode ("None", "Static", first published in XenServer 7.0)
        QString Ipv6ConfigurationMode() const;

        //! Get IPv6 addresses in CIDR format (first published in XenServer 7.0)
        QStringList Ipv6Addresses() const;

        //! Get IPv6 gateway (empty string means no gateway is set, first published in XenServer 7.0)
        QString Ipv6Gateway() const;

        // Object resolution getters
        QSharedPointer<Network> GetNetwork() const;
        QSharedPointer<VM> GetVM() const;

        // XenObject interface
        XenObjectType GetObjectType() const override { return XenObjectType::VIF; }
};

#endif // VIF_H
